SELECT Item_name, Price FROM MENU_ITEM WHERE Price = (Select MAX(Price) FROM MENU_ITEM);
SELECT Item_name FROM MENU_ITEM, MENU_ORDER WHERE Cid IN (SELECT Cid FROM CUSTOMER WHERE Fname = 'Guy'AND Lname = 'Fieri') AND MENU_ITEM.ItemID = MENU_ORDER.ItemID;
SELECT Fname, Lname FROM EMPLOYEE, MENU_ORDER WHERE MENU_ORDER.Eid = EMPLOYEE.Eid AND MENU_ORDER.Cid = 'C4';
SELECT Item_name, Ingredient_name FROM MENU_ITEM, INGREDIENT, MADE_OF WHERE MENU_ITEM.ItemID = MADE_OF.ItemID AND INGREDIENT.IngredientID = MADE_OF.IngredientID;
SELECT * FROM Ingredient WHERE Expiration = (SELECT MIN(Expiration) FROM Ingredient);