/*drop tables*/

DROP IF EXISTS MENU;
DROP IF EXISTS INGREDIENT;
DROP IF EXISTS STORAGE;
DROP IF EXISTS EMPLOYEE;
DROP IF EXISTS CUSTOMER;
DROP IF EXISTS SALES;

/*drop triggers*/

DROP TRIGGER IF EXISTS SALESTRIGGER;
DROP TRIGGER IF EXISTS DELETESALESTRIGGER;