/*drop tables*/

DROP IF EXISTS EMPLOYEE;
DROP IF EXISTS MANAGER;
DROP IF EXISTS CUSTOMER;
DROP IF EXISTS MENU_ITEM;
DROP IF EXISTS MENU_ORDER;
DROP IF EXISTS INGREDIENT;
DROP IF EXISTS RESERVATION;
DROP IF EXISTS PREPARED_BY;
DROP IF EXISTS MADE_OF;

