/*drop tables*/

DROP TABLE IF EXISTS MENU;
DROP TABLE  IF EXISTS INGREDIENT;
DROP TABLE  IF EXISTS STORAGE;
DROP TABLE  IF EXISTS EMPLOYEE;
DROP TABLE  IF EXISTS CUSTOMER;
DROP TABLE  IF EXISTS SALES;
DROP TABLE  IF EXISTS RESERVATION;

/*drop triggers*/

DROP TRIGGER IF EXISTS SALESTRIGGER;
DROP TRIGGER IF EXISTS ITEMTRIGGER;