/* create tables */

CREATE TABLE EMPLOYEE (
    Eid VARCHAR(20) PRIMARY KEY NOT NULL UNIQUE ,
    Fname VARCHAR(20) NOT NULL,
    Lname VARCHAR(20) NOT NULL,
    Job_type VARCHAR(20) NOT NULL,
    Pay_rate FLOAT(5) NOT NULL,
    Mid VARCHAR(20) REFERENCES MANAGER(Mid)
);

CREATE TABLE MANAGER (
    Eid VARCHAR(20) NOT NULL REFERENCES EMPLOYEE(Eid),
    Mid VARCHAR(20) NOT NULL,
    PRIMARY KEY (Eid)
);

CREATE TABLE CUSTOMER (
    Cid VARCHAR(20) PRIMARY KEY NOT NULL UNIQUE,
    Fname VARCHAR(20) NOT NULL,
    Lname VARCHAR(20) NOT NULL
);

CREATE TABLE MENU_ITEM (
    ItemID INTEGER(3) PRIMARY KEY NOT NULL UNIQUE,
    Item_type VARCHAR(10) NOT NULL,
    Item_name VARCHAR(20) NOT NULL,
    Price INTEGER(3) NOT NULL
);

CREATE TABLE MENU_ORDER (
    Oid VARCHAR(20) NOT NULL,
    ItemID INTEGER(3) NOT NULL,
    Count INTEGER(2) NOT NULL,
    Table_num INTEGER(3) NOT NULL,
    Eid VARCHAR(20) REFERENCES EMPLOYEE(Eid),
    Cid VARCHAR(20) NOT NULL REFERENCES CUSTOMER(Cid),
    PRIMARY KEY (Oid, ItemID)
);

CREATE TABLE INGREDIENT (
    IngredientID VARCHAR(20) NOT NULL,
    Expiration VARCHAR(10) NOT NULL,
    Ingredient_name VARCHAR(20) NOT NULL,
    Count Integer(3),
    PRIMARY KEY (IngredientID, Expiration)
);

CREATE TABLE RESERVATION (
    Rid VARCHAR(20) PRIMARY KEY,
    Cid VARCHAR(20) NOT NULL REFERENCES CUSTOMER(Cid),
    Date VARCHAR(10) NOT NULL,
    Time VARCHAR(5) NOT NULL,
    Num_party INTEGER(2) NOT NULL
);

CREATE TABLE PREPARED_BY (
    Oid VARCHAR(20) NOT NULL REFERENCES MENU_ORDER(Oid),
    ItemID VARCHAR(20) NOT NULL REFERENCES MENU_ITEM(ItemID),
    Eid VARCHAR(20) NOT NULL REFERENCES EMPLOYEE(Eid),
    PRIMARY KEY (Oid, ItemID, Eid)
);

CREATE TABLE MADE_OF (
    ItemID VARCHAR(20) NOT NULL REFERENCES MENU_ITEM(ItemID),
    IngredientID VARCHAR(20) NOT NULL REFERENCES INGREDIENT(IngredientID),
    PRIMARY KEY (ItemID, IngredientID)
);