CREATE TRIGGER SALESTRIGGER 
AFTER INSERT ON SALES 
FOR EACH ROW
UPDATE MENU 
SET sold = sold + 1 
WHERE item = NEW.item; 
CREATE TRIGGER ITEMTRIGGER
AFTER INSERT ON SALES
FOR EACH ROW
UPDATE STORAGE 
SET quantity = quantity - 1 
WHERE name IN (SELECT name FROM INGREDIENT WHERE item = NEW.item); 